# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjhjNDI3MTg3Y2M4YjhhODg5MDE2NzFlMTQzZWYxZGUxODZhNDE5YWI5MjEwMzA1ZDI2YzNlOGM3NjIwYjJkZDdhM2M3NzU3YmU0MjAwZmMwYjgyNDI3NDU2OTRhM2U5NmM5ZDcxZGFmMmNjOGU4Y2I5YzFiNDQwZDA5ZjkyMTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
